import { useNavigate } from "react-router-dom";
import { AppHeader } from "@/components/civic/AppHeader";
import { SearchBox } from "@/components/civic/SearchBox";
import { PromptCards } from "@/components/civic/PromptCards";
import { useRecentQuestions } from "@/hooks/useRecentQuestions";
import { Clock, ShieldCheck, Sparkles } from "lucide-react";

export default function Index() {
  const navigate = useNavigate();
  const { items: recent, clear } = useRecentQuestions();

  function ask(q: string) {
    navigate(`/results?q=${encodeURIComponent(q)}`);
  }

  return (
    <div className="min-h-screen flex flex-col">
      <AppHeader />
      <main className="flex-1 hero-gradient">
        <div className="container max-w-5xl py-16 sm:py-24">
          <div className="text-center space-y-4 animate-in-up">
            <div className="inline-flex items-center gap-2 rounded-full border border-border/70 bg-surface/60 backdrop-blur px-3 py-1 text-xs text-muted-foreground">
              <Sparkles className="h-3 w-3 text-primary" /> AI explains, code calculates
            </div>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-semibold tracking-tight max-w-3xl mx-auto text-balance">
              What would you like to understand about Washington's spending?
            </h1>
            <p className="text-muted-foreground max-w-2xl mx-auto text-lg text-balance">
              Ask in plain English. Every answer is backed by public vendor payment records — no invented numbers, no dashboards to configure.
            </p>
          </div>

          <div className="mt-10">
            <SearchBox onSubmit={ask} autoFocus />
          </div>

          <div className="mt-10">
            <h2 className="text-xs uppercase tracking-wider text-muted-foreground font-medium mb-3">Try a question</h2>
            <PromptCards onPick={ask} />
          </div>

          {recent.length > 0 && (
            <div className="mt-12">
              <div className="flex items-center justify-between mb-3">
                <h2 className="text-xs uppercase tracking-wider text-muted-foreground font-medium flex items-center gap-1.5"><Clock className="h-3 w-3" /> Recent</h2>
                <button className="text-xs text-muted-foreground hover:text-foreground transition" onClick={clear}>Clear</button>
              </div>
              <ul className="flex flex-wrap gap-2">
                {recent.map((r) => (
                  <li key={r}>
                    <button onClick={() => ask(r)} className="text-sm px-3 py-1.5 rounded-full border border-border/70 bg-surface/60 hover:border-primary/50 hover:text-primary transition">
                      {r}
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div className="mt-16 flex flex-wrap items-center justify-center gap-4 text-xs text-muted-foreground">
            <span className="inline-flex items-center gap-1.5"><ShieldCheck className="h-3.5 w-3.5 text-success" /> Numbers computed in code, never generated by AI</span>
            <span className="inline-flex items-center gap-1.5"><Sparkles className="h-3.5 w-3.5 text-primary" /> Explanations logged for governance</span>
          </div>
        </div>
      </main>
      <footer className="border-t border-border/60 no-print">
        <div className="container py-6 text-xs text-muted-foreground flex items-center justify-between">
          <span>CivicLens · A GoldenAnalytics Product Engineering Challenge submission</span>
          <span>Built for investigative journalism</span>
        </div>
      </footer>
    </div>
  );
}
