import { useNavigate } from "react-router-dom";
import { AppHeader } from "@/components/civic/AppHeader";
import { SearchBox } from "@/components/civic/SearchBox";
import { PromptCards } from "@/components/civic/PromptCards";
import { useRecentQuestions } from "@/hooks/useRecentQuestions";
import {
  Clock,
  ShieldCheck,
  Sparkles,
  Database,
  FileSearch,
  BarChart3,
} from "lucide-react";

export default function Index() {
  const navigate = useNavigate();
  const { items: recent, clear } = useRecentQuestions();

  function ask(question: string) {
    navigate(`/results?q=${encodeURIComponent(question)}`);
  }

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <AppHeader />

      <main className="flex-1 hero-gradient">
        <div className="container max-w-6xl py-16 sm:py-24">

          {/* Hero */}
          <div className="text-center space-y-6 animate-in-up">

            <div className="inline-flex items-center gap-2 rounded-full border border-primary/15 bg-primary/5 px-4 py-2 text-xs font-medium text-primary">
              <Sparkles className="h-3.5 w-3.5" />
              AI explains. Code calculates.
            </div>

            <h1 className="mx-auto max-w-4xl text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight leading-tight text-balance">
              Ask.
              <br />
              Understand.
              <br />
              Trust Public Spending.
            </h1>

            <p className="mx-auto max-w-3xl text-lg text-muted-foreground leading-8">
              Explore nearly <strong>one million Washington State vendor payment records</strong>
              using natural language. CivicLens combines deterministic calculations
              with AI-generated explanations, so every insight is grounded in real
              public data—not hallucinated numbers.
            </p>
          </div>

          {/* Search */}
          <div className="mt-12">
            <SearchBox onSubmit={ask} autoFocus />
          </div>

          {/* Example Prompts */}
          <div className="mt-10">
            <h2 className="mb-3 text-xs uppercase tracking-widest text-muted-foreground font-semibold">
              Try asking
            </h2>

            <PromptCards onPick={ask} />
          </div>

          {/* Trust Cards */}

          <div className="grid gap-4 md:grid-cols-4 mt-14">

            <div className="rounded-2xl border bg-card p-5 shadow-sm">
              <Database className="h-5 w-5 text-primary mb-3" />
              <h3 className="font-semibold">
                Nearly 1M Records
              </h3>
              <p className="text-sm text-muted-foreground mt-2">
                Analyze Washington State vendor payments from FY2022–FY2023.
              </p>
            </div>

            <div className="rounded-2xl border bg-card p-5 shadow-sm">
              <ShieldCheck className="h-5 w-5 text-green-600 mb-3" />
              <h3 className="font-semibold">
                Verified Calculations
              </h3>
              <p className="text-sm text-muted-foreground mt-2">
                Totals, averages, rankings and trends are calculated in code,
                never generated by AI.
              </p>
            </div>

            <div className="rounded-2xl border bg-card p-5 shadow-sm">
              <BarChart3 className="h-5 w-5 text-blue-600 mb-3" />
              <h3 className="font-semibold">
                Automatic Visuals
              </h3>
              <p className="text-sm text-muted-foreground mt-2">
                CivicLens automatically selects the most appropriate
                visualization for every answer.
              </p>
            </div>

            <div className="rounded-2xl border bg-card p-5 shadow-sm">
              <FileSearch className="h-5 w-5 text-orange-500 mb-3" />
              <h3 className="font-semibold">
                Transparent Evidence
              </h3>
              <p className="text-sm text-muted-foreground mt-2">
                Every AI explanation is backed by the underlying public
                payment records used to produce it.
              </p>
            </div>

          </div>

          {/* Recent Questions */}

          {recent.length > 0 && (
            <section className="mt-14">

              <div className="flex items-center justify-between mb-4">

                <h2 className="flex items-center gap-2 text-xs uppercase tracking-widest text-muted-foreground font-semibold">
                  <Clock className="h-3.5 w-3.5" />
                  Recent Questions
                </h2>

                <button
                  onClick={clear}
                  className="text-xs text-muted-foreground hover:text-primary transition-colors"
                >
                  Clear
                </button>

              </div>

              <div className="flex flex-wrap gap-3">

                {recent.map((item) => (
                  <button
                    key={item}
                    onClick={() => ask(item)}
                    className="rounded-full border px-4 py-2 text-sm hover:border-primary hover:text-primary transition-all"
                  >
                    {item}
                  </button>
                ))}

              </div>

            </section>
          )}

          {/* Product Promise */}

          <div className="mt-20 rounded-3xl border bg-card p-8 text-center shadow-sm">

            <h2 className="text-2xl font-semibold mb-4">
              Every answer includes
            </h2>

            <div className="grid gap-6 md:grid-cols-4">

              <div>
                <div className="text-2xl mb-2">🧠</div>
                <h3 className="font-medium">
                  Plain-English Summary
                </h3>
              </div>

              <div>
                <div className="text-2xl mb-2">📊</div>
                <h3 className="font-medium">
                  Automatic Charts
                </h3>
              </div>

              <div>
                <div className="text-2xl mb-2">📄</div>
                <h3 className="font-medium">
                  Source Evidence
                </h3>
              </div>

              <div>
                <div className="text-2xl mb-2">💡</div>
                <h3 className="font-medium">
                  Suggested Follow-ups
                </h3>
              </div>

            </div>

          </div>

        </div>
      </main>

      <footer className="border-t border-border/60">

        <div className="container py-6 flex flex-col md:flex-row items-center justify-between text-xs text-muted-foreground gap-2">

          <span>
            CivicLens • GoldenAnalytics Product Engineering Challenge
          </span>

          <span>
            Designed for investigative journalists and non-technical users
          </span>

        </div>

      </footer>
    </div>
  );
}